version: 0.0
os: linux

files:
  - source:  /build
    destination: /home/ubuntu/app
    overwrite: no

permissions:
  - object: /home/ubuntu/app/
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
