version: 0.0
os: linux

files:
  - source: ./build  # 수정: 빌드 결과물의 실제 경로로 변경
    destination: /home/ubuntu/nginx/build
    overwrite: yes

permissions:
  - object: /home/ubuntu/nginx/build/
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
